dist: trusty
sudo: require
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - git
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - cd ..
  - git clone https://github.com/g-truc/glm --depth=1
  - git clone https://github.com/glfw/glfw --depth=1
  - mkdir glm_build
  - cd glm_build
  - cmake ../glm
  - cmake --build .
  - sudo cmake --build . -- install
  - cd ..
  - git clone --recursive -j8 https://github.com/malt3d/malt_cmake --depth=1
  - git clone --recursive -j8 https://github.com/malt3d/malt_tool --depth=1
  - git clone --recursive -j8 https://github.com/malt3d/malt_core --depth=1
  - ./malt_tool/malt.py init
  - ./malt_tool/malt.py module build malt_basic
  - ./malt_tool/malt.py module test malt_basic
